[target.aarch64-linux-android]
linker = "aarch64-linux-android-clang"
rustflags = ["-C", "link-arg=-Wl,--allow-shlib-undefined"]

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi-clang"
rustflags = ["-C", "link-arg=-Wl,--allow-shlib-undefined"]

[target.x86_64-linux-android]
linker = "x86_64-linux-android-clang"
rustflags = ["-C", "link-arg=-Wl,--allow-shlib-undefined"]

[target.i686-linux-android]
linker = "i686-linux-android-clang"
rustflags = ["-C", "link-arg=-Wl,--allow-shlib-undefined"]

[build]
rustflags = ["-C", "target-cpu=native"]

[env]
RUST_BACKTRACE = "1"